config:
  credentials: []
  project_repos:
    code-repo.d4science.org/michele.artini/simpleOaiCollectorService:
      branch: main
      repo: https://code-repo.d4science.org/michele.artini/simpleOaiCollectorService
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-vermilion-boar.sh
        container: qc.acc_grumpy-apricot-beetle
  QC.Doc:
    repos:
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-champagne-newfoundland.sh
        container: qc.doc_skanky-ultramarine-ant
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService git:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-eggplant-ray.sh
        container: qc.doc_breezy-goldenrod-vole
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-persimmon-walrus.sh
        container: qc.doc_bumpy-heliotrope-civet
  QC.Lic:
    repos:
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-cerise-schnauzer.sh
        container: qc.lic_paltry-charcoal-cuscus
  QC.Sty:
    repos:
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-cobalt-gibbon.sh
        container: qc.sty_randy-wheat-squirt
  QC.Ver:
    repos:
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-linen-tarantula.sh
        container: qc.ver_silly-sapphire-chihuahua
timeout: 5400
