config:
  credentials: []
  project_repos:
    code-repo.d4science.org/michele.artini/simpleOaiCollectorService:
      branch: main
      repo: https://code-repo.d4science.org/michele.artini/simpleOaiCollectorService
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-bistre-kakapo.sh
        container: qc.acc_messy-silver-beetle
  QC.Doc:
    repos:
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-pumpkin-chameleon.sh
        container: qc.doc_scaly-lime-dhole
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-tomato-earwig.sh
        container: qc.doc_grumpy-rust-stingray
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-denim-jackal.sh
        container: qc.doc_geeky-tan-butterfly
  QC.Lic:
    repos:
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService licensee:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-azure-ferret.sh
        container: qc.lic_squirrely-viridian-barracuda
  QC.Sty:
    repos:
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService checkstyle:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-olive-squirrel.sh
        container: qc.sty_chewy-goldenrod-warthog
  QC.Ver:
    repos:
      code-repo.d4science.org/michele.artini/simpleOaiCollectorService get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-plum-coyote.sh
        container: qc.ver_dorky-alizarin-antelope
timeout: 5400
